#!/bin/bash
set -e

VERILOG_CMD="iverilog -g2005-sv"

compare () {
    reference_out=$1
    vpiler_out=$2
    if [ "$reference_out" = "$vpiler_out" ]; then
        echo "$vpiler_out"
        echo "reference and vpiler match"
    else
        echo "MISMATCH: reference out: $reference_out, vpiler out: $vpiler_out"
        exit 1
    fi
}

echo "compiling and running hello_world.sv with icarus verilog"
$VERILOG_CMD -o hello_world hello_world.sv
icarus_out=$(./hello_world)

echo
echo "compiling and running hello_world.sv with vpiler"
./main.py "$@" hello_world.sv
vpiler_out=$(./a.out)

compare "$icarus_out" "$vpiler_out"

echo
echo "compiling and running counter.sv with icarus verilog"
$VERILOG_CMD -o counter counter.sv
icarus_out=$(./counter)

echo
echo "compiling and running counter.sv with vpiler"
./main.py "$@" counter.sv
vpiler_out=$(./a.out)

compare "$icarus_out" "$vpiler_out"

echo 
echo "compiling and running hello_world.vhdl with ghdl"
ghdl -a hello_world.vhdl
ghdl -e hello_world
ghdl_out=$(ghdl -r hello_world)
echo "$ghdl_out"

echo
echo "compiling and running hello_world.vhdl with vpiler"
echo "not done yet"

compare "$ghdl_out" "$vpiler_out"
